export const metadata = {
  title: 'NBA 2k Player App',
  description: 'Generated by Next.js',
  icon: 'https://p7.hiclipart.com/preview/663/591/824/5bbc0e1f32507.jpg',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <><head>
      <title>{metadata.title}</title>
      <link rel="icon" href={metadata.icon} />
    </head><html lang="en">
        <body>{children}</body>
      </html></>
  )
}
